config/routes.rb
BoiCms20::Application.routes.draw do

  resources :birds, only: [:show, :index]
  resources :evaluation_sets, only: [:show] do 
    resources :user_evaluations, only: [:show] 
    resources :user_evaluation_answers, only: [:index]
  end

  ActiveAdmin.routes(self)

  namespace :admin do
    resources :birds do
      resources :assets
    end
    resources :evaluation_sets do
      resources :user_evaluations do 
        collection do 
          get 'comments'
        end
      end
      resources :user_evaluation_answers do 
        collection do 
          get 'summary'
        end
      end
    end
  end 

  devise_for :users, ActiveAdmin::Devise.config

  root :to => "evaluation_sets#show", id: 1

end

app/models/bird.rb
class Bird < ActiveRecord::Base

  has_paper_trail
  
  #default_scope includes(:logo).order("birds.name ASC")

  belongs_to :genus_type
  belongs_to :habitat
  belongs_to :fse_org_style, :class_name => "OrgStyle", :foreign_key => "fse_org_style_id"
  belongs_to :op_org_style, :class_name => "OrgStyle", :foreign_key => "op_org_style_id"

  belongs_to :updated_by, :class_name => "User", :foreign_key => "updated_by_id"

  has_many :user_evaluations, :dependent => :destroy
  has_many :evaluation_results, :inverse_of => :bird

  has_one :logo, 
    :class_name => "Asset", 
    :as => "attached_to", 
    :conditions => {:role => "logo"},
    :dependent => :destroy    

  has_many :images,
    :class_name => "Asset",
    :as => "attached_to",
    :conditions => {:role => nil},
    :dependent => :destroy

  validates_presence_of :name

  accepts_nested_attributes_for :logo, :allow_destroy => true
  accepts_nested_attributes_for :images, :allow_destroy => true

  attr_accessor :uploaded_logo #upload to this attr for replacing logos
  def uploaded_logo=(img)
    logo.destroy unless logo.nil?
    f = Asset.new(:asset => img, :attached_to => self, :role => "logo")
    f.save
  end
 
  scope :recently_updated, lambda { |n| order("updated_at DESC").limit(n) }
 

  def thumbnail_100_url
    begin
      logo.asset.url(:sq100, false)
    rescue
      nil
    end
  end

  def thumbnail_50_url
    begin
      logo.asset.url(:sq50, false)
    rescue
      nil
    end
  end


  # def as_json(options = {})
  #   super({
  #     :methods => [:thumbnail_100_url, :thumbnail_50_url],
  #     :only => [:id,:name]
  #   })
  # end



end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  respond_to :json

  def show
    respond_with Bird.find(params[:id]), root: false 
  end

  def index
    respond_with Bird.order("name ASC"), root: false, :each_serializer => BirdArraySerializer
  end

end

app/views/admin/birds/_form.html.erb
  <script>
    <%- session_key = Rails.application.config.session_options[:key] -%>
    BOI_SESSION_KEY = "<%= session_key %>";
    BOI_SESSION_VAL = '<%= cookies[session_key] %>';
  </script>  
  

 <%= semantic_form_for [:admin, @bird], :html => {:multipart => true}, :remote=> !@bird.new_record? do |f| %>


    <%= f.inputs "Basic Info" do %>
      <div class="fieldset_hint"><%= I18n.translate!("boi_schema.sections.basic_info.description") %></div>
      
      <%= f.input :name, :as => :string, 
        :label => I18n.translate!("boi_schema.fields.name.human") %>
      <%= f.input :url, :as => :string, 
        :label => I18n.translate!("boi_schema.fields.url.human") %>
 
      <!-- mamual input for logo upload--!>
      <li class="file input optional" id="bird_uploaded_logo_input">
        <label class="label" for="bird_uploaded_logo"><%= I18n.translate!("boi_schema.fields.logo.human") %></label>
        <div style="margin:0.5em 0 0 20%">
          <%= image_tag(@bird.logo.asset.url(:sq300)) unless @bird.logo.nil? %>
          <input id="bird_uploaded_logo" name="bird[uploaded_logo]" type="file" />
        </div>
      </li>

      <!-- mamual input for file upload--!>
      <li class="file input optional" id="images_input">
        <label class="label" for="bird_images">
          <%= I18n.translate!("boi_schema.fields.images.human") %>
        </label>
        <div style="margin:0.5em 0 0 20%">
          <div id="media_files">
            <%= render :partial => "admin/assets/form", :locals => {:assets => @bird.images, :attached_to => @bird } %>
          </div>
          <% if @bird.new_record? %>
            <em>You will be able to add images after saving</em>
          <% else %>
            <div id="media_file_uploader"></div>
          <% end %>
        </div>
      </li>
   
      <%= f.input :habitat, 
        :label => I18n.translate!("boi_schema.fields.habitat.human"),
        :hint => I18n.translate!("boi_schema.fields.habitat.description") %>
        
      <%= f.input :genus_type, 
        :label => I18n.translate!("boi_schema.fields.genus_type.human"),
        :hint => I18n.translate!("boi_schema.fields.genus_type.description") %>
        
      <%= f.input :brand, 
        :label => I18n.translate!("boi_schema.fields.brand.human"),
        :hint => I18n.translate!("boi_schema.fields.brand.description") %>
    <%end%>
 
 
     <%= f.inputs "Structure" do %>
      <div class="fieldset_hint"><%= I18n.translate!("boi_schema.sections.structure.description") %></div>

      <%= f.input :fse_name, 
        :label => I18n.translate!("boi_schema.fields.fse_name.human"), 
        :hint => I18n.translate!("boi_schema.fields.fse_name.description") %>
      <%= f.input :fse_org_style, 
        :label => I18n.translate!("boi_schema.fields.fse_org_style.human"), 
        :hint => I18n.translate!("boi_schema.fields.fse_org_style.description") %>
      <%= f.input :fse_owner_founder, 
        :label => I18n.translate!("boi_schema.fields.fse_owner_founder.human"), 
        :hint => I18n.translate!("boi_schema.fields.fse_owner_founder.description")%>
      <%= f.input :fse_significant_member, 
        :label => I18n.translate!("boi_schema.fields.fse_significant_member.human"), 
        :hint => I18n.translate!("boi_schema.fields.fse_significant_member.description") %>
      <%= f.input :fse_mission_statement, 
        :label => I18n.translate!("boi_schema.fields.fse_mission_statement.human"), 
        :hint => I18n.translate!("boi_schema.fields.fse_mission_statement.description") %>
      <%= f.input :op_name, 
        :label => I18n.translate!("boi_schema.fields.op_name.human"), 
        :hint => I18n.translate!("boi_schema.fields.op_name.description") %>
      <%= f.input :op_org_style, 
        :label => I18n.translate!("boi_schema.fields.op_org_style.human"), 
        :hint => I18n.translate!("boi_schema.fields.op_org_style.description") %>
      <%= f.input :op_vip_founders, 
        :label => I18n.translate!("boi_schema.fields.op_vip_founders.human"), 
        :hint => I18n.translate!("boi_schema.fields.op_vip_founders.description") %>
      <%= f.input :op_typical_member, 
        :label => I18n.translate!("boi_schema.fields.op_typical_member.human"), 
        :hint => I18n.translate!("boi_schema.fields.op_typical_member.description") %>
      <%= f.input :foritself,
        :label => I18n.translate!("boi_schema.fields.foritself.human"),
        :hint => I18n.translate!("boi_schema.fields.foritself.description") %>     
    <%end%>
    

     <%= f.inputs "Ontogeny" do %>
      <div class="fieldset_hint"><%= I18n.translate!("boi_schema.sections.ontogeny.description") %></div>
      
      <%= f.input :formation, 
        :label => I18n.translate!("boi_schema.fields.formation.human"), 
        :hint => I18n.translate!("boi_schema.fields.formation.description") %>
      <%= f.input :history, 
        :label => I18n.translate!("boi_schema.fields.history.human"), 
        :hint => I18n.translate!("boi_schema.fields.history.description") %>
      <%= f.input :lifespan, 
        :label => I18n.translate!("boi_schema.fields.lifespan.human"), 
        :hint => I18n.translate!("boi_schema.fields.lifespan.description") %>
    <%end%>
    
    
 
     <%= f.inputs "Behavior" do %>
      <div class="fieldset_hint"><%=  I18n.translate!("boi_schema.sections.behavior.description") %></div>
 
      <%= f.input :resource, 
        :label => I18n.translate!("boi_schema.fields.resource.human"), 
        :hint => I18n.translate!("boi_schema.fields.resource.description") %>
      <%= f.input :availability, 
        :label => I18n.translate!("boi_schema.fields.availability.human"), 
        :hint => I18n.translate!("boi_schema.fields.availability.description") %>
      <%= f.input :participation, 
        :label => I18n.translate!("boi_schema.fields.participation.human"), 
        :hint => I18n.translate!("boi_schema.fields.participation.description") %>
      <%= f.input :tasks, 
        :label => I18n.translate!("boi_schema.fields.tasks.human"), 
        :hint => I18n.translate!("boi_schema.fields.tasks.description") %>
      <%= f.input :modularity, 
        :label => I18n.translate!("boi_schema.fields.modularity.human"), 
        :hint => I18n.translate!("boi_schema.fields.modularity.description") %>
      <%= f.input :granularity, 
        :label => I18n.translate!("boi_schema.fields.granularity.human"), 
        :hint => I18n.translate!("boi_schema.fields.granularity.description") %>
      <%= f.input :metrics, 
        :label => I18n.translate!("boi_schema.fields.metrics.human"), 
        :hint => I18n.translate!("boi_schema.fields.metrics.description") %>
        
       <!-- mamual input for tangible problem--!>
      <li class="text input optional" id="bird_tangible_problem_input">
        <label class="label" for="bird_tangible_prolem"><%= I18n.translate!("boi_schema.fields.tangible_problem.human") %></label>
        <div style="margin:0.5em 0 0 20%">
          <%= f.select :tangible_problem, ["","Yes","No"] %>
          <%= f.text_field :tangible_problem_detail, :style => "margin-left:15px;" %>
        </div>
        <p class="inline-hints">
          <%= I18n.translate!("boi_schema.fields.tangible_problem.description") %>
        </p>
      </li>
        

    <%end%>   
    
    
    <%= f.inputs "Mating" do %>
      <div class="fieldset_hint"><%= I18n.translate!("boi_schema.sections.mating.description") %></div>
      <%= f.input :alliances, 
        :label => I18n.translate!("boi_schema.fields.alliances.human"), 
        :hint => I18n.translate!("boi_schema.fields.alliances.description") %>   
      <%= f.input :clients, 
        :label => I18n.translate!("boi_schema.fields.clients.human"), 
        :hint => I18n.translate!("boi_schema.fields.clients.description") %>
      <%= f.input :sponsors, 
        :label => I18n.translate!("boi_schema.fields.sponsors.human"), 
        :hint => I18n.translate!("boi_schema.fields.sponsors.description") %>
      <%= f.input :elites, 
        :label => I18n.translate!("boi_schema.fields.elites.human"), 
        :hint => I18n.translate!("boi_schema.fields.elites.description") %>     
    <%end%> 
    
    
    <%= f.inputs "Summary" do %>
      <div class="fieldset_hint">The summary should give an simple introduction. One sentence to describe what the bird is and what it does; a paragraph describing its ontogeny and structure, and a paragraph summarizing its behavior and mating. One can also add information here that is not elicited by these questions, but seems important in order to understand the bird. Other kinds of information that may also be appropriate her: analytical or theoretical assessments, questions, and ideas or suggestions for transforming the schema in based on something revealed by this bird.</div>
      <%= f.input :summary %>
    <%end%>
    
    
    <%= f.inputs "Metadata" do %>
      <%= f.input :birder_credits, :hint => "Indicate authorial credit(s) for this entry" %>
      
      <input id="bird_updated_by_id" name="bird[updated_by_id]" type="hidden" value="<%= current_user.id %>">      
    <%end%> 
         
    <%= f.action(:submit) %>
    <%= f.action(:cancel) %>
         
<% end %>

<script>
  // this is here so that it runs even after each XHR request
  set_bird_form_bindings();
  
  // for last_saved side_panel
  var last_saved = "<%= @bird.updated_at.nil? ? 'never' :  @bird.updated_at.localtime.to_formatted_s(:long) %>"
  
  // for xhr requests
  set_bird_form_last_saved(last_saved)
  // for normal doc loading
  $(document).ready(function(){ set_bird_form_last_saved(last_saved) })
</script>

app/views/admin/birds/_save_sidebar.html.erb
<%= link_to "Save Now", "#", :onclick => "$('form.bird').submit();return false;" %>
<% unless @bird.new_record? %>
    &nbsp; | &nbsp;
  <a href="#" style="font-weight:normal;" onclick="save_and_redirect($('form.bird'),'<%= admin_bird_url(@bird) %>');return false;">Save and Preview</a>
<% end %>
  
<div class="edit_saved_status">&nbsp;</div>