config/routes.rb
BoiCms20::Application.routes.draw do

  resources :birds, only: [:show, :index]
  resources :evaluation_sets, only: [:show] do 
    resources :user_evaluations, only: [:show] 
    resources :user_evaluation_answers, only: [:index]
  end

  ActiveAdmin.routes(self)

  namespace :admin do
    resources :birds do
      resources :assets
    end
    resources :evaluation_sets do
      resources :user_evaluations do 
        collection do 
          get 'comments'
        end
      end
      resources :user_evaluation_answers do 
        collection do 
          get 'summary'
        end
      end
    end
  end 

  devise_for :users, ActiveAdmin::Devise.config

  root :to => "evaluation_sets#show", id: 1

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :attached_to, :polymorphic => true
  has_attached_file :asset, 
    :styles => { :sq600 => "600x600", :sq300 => "300x300>", :sq100 => "100x100>", :sq50 => "50x50>" },
    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename"
  
  before_post_process :is_image?


  def original_url
    asset.url(:original)
  end
  
  def is_image?
    !(asset_content_type =~ /^\[?image.*/).nil?
  end

end

app/controllers/admin/assets_controller.rb
class Admin::AssetsController < ApplicationController

  before_filter :get_bird

  # GET /assets
  # GET /assets.xml
  def index
    @assets = Asset.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @assets }
    end
  end

  # GET /assets/1
  # GET /assets/1.xml
  def show
    @asset = Asset.find(params[:id], :include => :user)
    @total_assets = Asset.find(:all, :conditions => { :user_id => @asset.user.id})
  end

  # GET /assets/new
  # GET /assets/new.xml
  def new
    @asset = Asset.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = Asset.find(params[:id])
  end

  # POST /assets
  # POST /assets.xml
  def create
      @bird
      newparams = coerce(params)
      @asset = Asset.new(newparams[:asset])
      if @asset.save
        flash[:notice] = "Successfully created asset."
        respond_to do |format|
          format.all {
            render :partial => "admin/assets/form.html.erb", :locals => {:assets => @bird.images, :attached_to => @bird }
          }
          #format.json {
          #  render :json => { :result => 'success', :asset => asset_path(@asset) } 
          #}
        end
      else
        render :action => 'new'
      end
    end

  # PUT /assets/1
  # PUT /assets/1.xml
  def update
    @asset = Asset.find(params[:id])
    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to(@asset, :notice => 'Asset was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.xml
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html {
        if request.xhr?
          render :partial => "admin/birds/form"
        else
          redirect_to admin_edit_bird_url(@bird)
        end
      }
      format.xml  { head :ok }
    end
  end

  private 
  
  def get_bird
    @bird = Bird.find(params[:bird_id])
  end

  def coerce(params)
    if params[:upload].nil? 
      h = Hash.new 
      h[:asset] = Hash.new 
      h[:asset][:attached_to] = @bird
      h[:asset][:asset] = params[:Filedata] 
      h[:asset][:asset].content_type = MIME::Types.type_for(h[:asset][:asset].original_filename).to_s
      h
    else 
      params
    end 
  end
  

end

app/views/admin/assets/_assets.html.erb
<ul class="file_list">
<% assets.each_with_index do |ass, i| %>
  <li>
    <%= link_to ass.asset_file_name, ass.asset.url(), :target => "_blank" %>
    <% if ass.is_image? %>
      <%= image_tag ass.asset.url("sq50"), :height=>"20px" %>
    <% else %>
      <%= image_tag "doc-icon.png" %>
    <% end %>
  </li>
<% end %>
</ul>

app/views/admin/assets/_form.html.erb
<% assets.each_with_index do |ass, i| %>

  <p>
    <% if ass.is_image? %>
      <%= image_tag ass.asset.url("sq50"), :height=>"20px" %>
    <% else %>
      <%= image_tag "doc-icon.png" %>
    <% end %>
    <%= link_to ass.asset_file_name, ass.asset.url() %>
    <%= link_to  admin_bird_asset_path(attached_to, ass), 
        :method => :delete, :remote=> true, 
        :confirm => "Are you sure you want to delete the file #{ass.asset_file_name} ?", 
        :alt => "delete",
        :class => "remote-delete"  do %>
        <img src="/images/red-x.png" />
    <% end %>

  <p>
<% end %>