config/routes.rb
BoiCms20::Application.routes.draw do

  resources :birds, only: [:show, :index]
  resources :evaluation_sets, only: [:show] do 
    resources :user_evaluations, only: [:show] 
    resources :user_evaluation_answers, only: [:index]
  end

  ActiveAdmin.routes(self)

  namespace :admin do
    resources :birds do
      resources :assets
    end
    resources :evaluation_sets do
      resources :user_evaluations do 
        collection do 
          get 'comments'
        end
      end
      resources :user_evaluation_answers do 
        collection do 
          get 'summary'
        end
      end
    end
  end 

  devise_for :users, ActiveAdmin::Devise.config

  root :to => "evaluation_sets#show", id: 1

end

app/models/evaluation_set.rb
class EvaluationSet  < ActiveRecord::Base;


  # An EvaluationSet is a collection of questions 
  has_many :evaluation_questions, 
           :order => "position ASC",
           :inverse_of => :evaluation_set
           
  has_many :evaluation_results, :through => :evaluation_questions

  accepts_nested_attributes_for :evaluation_questions, :allow_destroy => true



  # The questions a related to user answers through user's evaluations
  has_many :user_evaluations
  has_many :user_evaluation_answers, :through => :user_evaluations

  # the user who created the evaluation set
  belongs_to :owner, :class_name => "User", :foreign_key => "owner_id"

  # the birds that have have been evaluated
  has_many :birds, :through => :user_evaluations, :uniq => true, :order => "name ASC"

  # the users who have done evaluations based on this set
  has_many :users, :through => :user_evaluations, :uniq => true

  validate :update_on_unlock_only
  before_destroy :destroy_on_unlock_only 



  def self.response_group_for(result_rows)
    answer_keys = [:yes_count, :no_count, :na_count]
    scores = {:yes_count => 1, :no_count => 2, :na_count => 3}
    signature = ""
    result_rows[:questions].each_with_index do |q,i|
      ans_counts = q.reject{|k,v| !answer_keys.include?(k)}
      max_count = ans_counts.max_by{|k,v| v }[1]
      all_max_counts = ans_counts.keep_if{ |k,v| v == max_count }
      score = all_max_counts.size == 1 ? scores[all_max_counts.to_a[0][0]] : 0
      signature[i] = score.to_s
    end 
    return signature
  end


  def response_groups
    groups = {}
    results_by_bird.each do |r|
      group_sig = EvaluationSet.response_group_for(r)
      groups[group_sig] ||= []
      groups[group_sig] << r[:bird]
    end
    return groups.sort_by{|k,v| v.size }.reverse!
  end

  
  protected

  def update_on_unlock_only
    if locked
      message = "Cannot be changed when the evaluation set is locked"
      errors.add(:name, message) if name_changed?
      errors.add(:instructions, message) if instructions_changed?
    end
  end

  def destroy_on_unlock_only 
    if locked
      errors.add_to_base("Cannot delete while locked")
      return false
    end
  end


end

app/controllers/evaluation_sets_controller.rb
class EvaluationSetsController < ApplicationController

  respond_to :json, :html

  def show
    @id = params[:id]
    respond_with do |format|
      format.json{ respond_with EvaluationSet.find(params[:id]), root: false }
    end 
    
  end

end

app/views/admin/evaluation_sets/_results_filter_form.html.haml
.results_filter_wrapper 
  = semantic_form_for @evaluation_results, :url => url_for([:results_table, :admin, @evaluation_set ]), 
      :html => {:method => :get, :class => "results_filter toggle closed"} do |f|
    = f.inputs "Results Filters" do 

      - q_boxes = {"All" => "0"}.merge(Hash[@evaluation_set.evaluation_questions.map{|q| [q.to_s.truncate(70), q.id ]}])
      - b_boxes = {"All" => "0"}.merge(Hash[@evaluation_set.birds.map{|b| [b.name, b.id ]}])

      = f.input :evaluation_question_id_in, :as => :check_boxes, :collection => q_boxes, 
                  :wrapper_html => {:class => "multicolumn_2 toggle_all_checkbox"},
                  :value_as_class => true




      = f.input :bird_id_in, :as => :check_boxes, :collection => b_boxes,
                  :wrapper_html => {:class => "multicolumn_4 toggle_all_checkbox"},
                  :value_as_class => true


      -#
      -# Horrible HACK to get boxes checked    
      -#

      - bird_checks = @evaluation_results.search_attributes["bird_id_in"] 
      - question_checks = @evaluation_results.search_attributes["evaluation_question_id_in"]

      - if bird_checks && !bird_checks.empty?
        - bird_checks.each do |b_id|
          :javascript 
            $("input#search_bird_id_in_#{b_id}").attr("checked",true)
      - else
        :javascript
          $("#search_bird_id_in_0").attr("checked",true) 
      - if question_checks && !question_checks.empty?
        - question_checks.each do |q_id|
          :javascript 
            $("input#search_evaluation_question_id_in_#{q_id}").attr("checked",true)
      - else
        :javascript
          $("#search_evaluation_question_id_in_0").attr("checked",true)

      = f.actions do 
        = f.submit "Filter"

:javascript
  
  $(".toggle_all_checkbox .choices-group .choice input[type=checkbox]").on("click", function(){

    var $all_checks  = $(this).closest(".toggle_all_checkbox").find(".choices-group .choice input[type=checkbox]"),
        $reg_checks  = $all_checks.not(".choice:first-child input[type=checkbox]"),
        $first_check = $all_checks.not($reg_checks).first()

    var checked = $(this).attr("checked") === undefined ? false : true

    if ($(this).is($first_check) && checked) {
      $reg_checks.attr("checked", false)
    } 

    if ( !$(this).is($first_check) && checked) {
      $first_check.attr("checked", false)
    }     



  })

  $("form.results_filter").on("submit",function(){
    $(".results_table_wrapper").html("<div class='updating'>")
    $(this).find("fieldset.inputs > ol").slideUp('slow')
  })


  $("form.toggle").on("click","fieldset.inputs legend span",function(){ 
    $(this).closest(".toggle").find("fieldset.inputs > ol").slideToggle('slow')
    $(this).closest(".toggle").toggleClass("closed")
  })

app/views/admin/evaluation_sets/_results_table.html.haml
- questions =@evaluation_set.evaluation_questions
%table.index_table.evaluation_results{:border => "0", :cellpadding => "0", :cellspacing => "0"}
  %thead
    %tr
      %th &nbsp;
      %th{ :class => @custom_sort.empty? ? "sorted-asc" : "" }
        = sort_link @evaluation_results, :title, :default_order => :asc

      - @result_rows[0].results.each_with_index do |r, i|

        - sort_val = "custom_sort_result_column[#{i}]"
        - if !@custom_sort.empty? and @custom_sort[:type] == :result_column and @custom_sort[:index] == i
          - next_sort_order = @custom_sort[:order] == :asc ? :desc : :asc
          - th_class = "sorted-#{@custom_sort[:order]}"
        - else 
          - next_sort_order = :desc
          - th_class = ""

        - th_class += r.evaluation_question.sub_question ? " sub_question" : ""

        %th{ :class => th_class }
          = sort_link @evaluation_results, sort_val, "##{r.evaluation_question.position}",
            :default_order =>  next_sort_order

      -# summary header
      - if !@custom_sort.empty? and @custom_sort[:type] == :by_summary 
        - next_sort_order = @custom_sort[:order] == :asc ? :desc : :asc
        - th_class = "sorted-#{@custom_sort[:order]}"
      - else 
        - next_sort_order = :desc
        - th_class = ""

      %th{ :class => "summary #{th_class}" }
        = sort_link @evaluation_results, "custom_sort_by_summary", "Summary",
            :default_order => next_sort_order

  %tbody
    - @result_rows.each do |row|
      %tr
        %td= row.bird.logo.nil? ? "" : image_tag( row.bird.logo.asset.url(:sq50) ) 
        %td
          %b= link_to row.bird.name, [:admin, row.bird]
          %br/
          = link_to "comments",                                                                                       comments_admin_evaluation_set_user_evaluations_path(@evaluation_set, :bird_id => row.bird.id), 
            :remote => true,                                                                              
            :style => "font-size:0.8em;"

        - row.results.each do |result|
          %td{:class => result.evaluation_question.sub_question ? "sub_question" : ""}
            - title = capture do 
              =result.evaluation_question.to_s
              %br/
              %b Yes:
              = result.yes_count
              %b No:
              = result.no_count
              %b N/A
              =result.na_count
              %br/
              %b Score
              =result.answer_score

            = link_to summary_admin_evaluation_set_user_evaluation_answers_path(@evaluation_set, 
                :evaluation_question_id => result.evaluation_question_id, :bird_id => row.bird.id ),
                :remote =>true  do
              .evaluation_result_pie.tooltip_trigger{  :title => title,
                :class => (result.evaluation_question.sub_question ? "sub_question" : ""),
                "data-blank-count"  => result.blank_count, 
                "data-na-comments"  => result.na_comments, 
                "data-na-count"     => result.na_count, 
                "data-no-comments"  => result.no_comments,
                "data-no-count"     => result.no_count, 
                "data-yes-comments" => result.yes_comments, 
                "data-yes-count"    => result.yes_count }

        %td{:class => "summary"}
          - title = capture do 
            ="Summary:"
            %br/
            %b Yes:
            = row.summary["yes_count"]
            %b No:
            = row.summary["no_count"]
            %b N/A
            = row.summary["na_count"]
            %br/
            %b Score
            =row.summary["score"]
          .evaluation_result_pie.tooltip_trigger{ :title => title,
            :class => "summary",
            "data-blank-count"  => row.summary["blank_count"], 
            "data-na-comments"  => 0, 
            "data-na-count"     => row.summary["na_count"], 
            "data-no-comments"  => 0,
            "data-no-count"     => row.summary["no_count"], 
            "data-yes-comments" => 0, 
            "data-yes-count"    => row.summary["yes_count"] }

#evaluation_result_details.user_evaluation_answers_summary.user_evaluations_comments

:javascript 


  $(".evaluation_result_pie").each(function(){
    var $elem = $(this)
    setTimeout( function(){
      draw_answers_pie.apply($elem,[
          $elem.data("yes-count"), 
          $elem.data("no-count"),
          $elem.data("na-count"),
          $elem.data("blank-count"),
          $elem.data("yes-comments"),
          $elem.data("no-comments"),
          $elem.data("na-comments"),
      ])
    }, 1);
  })

  $(".tooltip_trigger[title]").tooltip()

app/views/admin/evaluation_sets/_results_twoaxis_details.html.haml
.panel
  %h3
    Evaluation Result Details
    %a.close{ :href =>"javascript:void(0)", :onclick => '$(this).closest("#evaluation_result_details").html("")' } close
  .panel_contents
    .attributes_table

      - questions =@evaluation_set.evaluation_questions
      %table.index_table.evaluation_results{:border => "0", :cellpadding => "0", :cellspacing => "0"}
        %tbody
          - @result_rows.each do |row|
            %tr
              %td
                %b= link_to row.bird.name, [:admin, row.bird]

              - [ row.results[@x_question_index],  row.results[@y_question_index] ].each do |result|
                %td{:class => result.evaluation_question.sub_question ? "sub_question" : ""}
                  - title = capture do 
                    =result.evaluation_question.to_s
                    %br/
                    %b Yes:
                    = result.yes_count
                    %b No:
                    = result.no_count
                    %b N/A
                    =result.na_count
                    %br/
                    %b Score
                    =result.answer_score

                  = link_to summary_admin_evaluation_set_user_evaluation_answers_path(@evaluation_set, 
                      :evaluation_question_id => result.evaluation_question_id, :bird_id => row.bird.id ),
                      :remote =>true  do
                    .evaluation_result_pie.tooltip_trigger{  :title => title,
                      :class => (result.evaluation_question.sub_question ? "sub_question" : ""),
                      "data-blank-count"  => result.blank_count, 
                      "data-na-comments"  => result.na_comments, 
                      "data-na-count"     => result.na_count, 
                      "data-no-comments"  => result.no_comments,
                      "data-no-count"     => result.no_count, 
                      "data-yes-comments" => result.yes_comments, 
                      "data-yes-count"    => result.yes_count }

app/views/admin/evaluation_sets/question_analysis.html.haml
:css

  .d3_vis {
    background:color:#eee;
    border-right:1px solid #bbb;
    border-bottom:1px solid #bbb;
    shape-rendering: crispEdges;

  }

  .axis path,
  .axis line {
      fill: none;
      stroke: black;
      shape-rendering: crispEdges;
  }

  .axis text {
      font-family: sans-serif;
      font-size: 11px;
  }


.span X-Axis
%select.question_analysis.x_axis
  - @results.each_with_index do |r,i|
    %option{:value => i}
      = "#{r.question.id}. #{r.question.to_s}"

.span Y-Axis
%select.question_analysis.y_axis
  %option{:value => -1} select
  - @results.each_with_index do |r,i|
    %option{:value => i}
      = "#{r.question.id}. #{r.question.to_s}"



.d3_vis{:style=>"width:1000px;height:600px;"}


:javascript
  d3.select(".d3_vis").datum(#{@results.to_json})

app/views/admin/evaluation_sets/result_groups.html.erb
<h1>Groups</h1>

<table class="index_table result_groups" border="0" cellspacing="0" cellpadding="0" >
  <tbody>
    <% result_groups.each do |row| %>
    <tr>
      <td> <b><%= row[1].size %></b></td>
      <td>
        <% row[1].each do |b| %>
          <%= link_to b.name, [:admin, b], :target => "_blank" %><br/>
        <% end %>
      </td>
      <% row[0].split(//).each_with_index do |num, i| %>
        <td class='tooltip_trigger' title='<%= @evaluation_set.evaluation_questions[i].question %>'>
          <% if num=="1" %>
            <span class="answer_yes">YES</span>
          <% elsif num == "2" %>
            <span class="answer_no">NO</span>
          <% elsif num == "3" %>
            <span class="answer_na">N/A</span>
          <% else %>
            <span class="answer_blank">?</span>
          <% end %>
        </td>
      <% end %>
    </tr>
    <%end%>
  </tbody>
</table>


<div id="evaluation_result_details" class="user_evaluation_answers_summary user_evaluations_comments">
 
</div>

app/views/admin/evaluation_sets/results_table.html.haml
= render "results_filter_form"

- if @result_rows.empty?
  %span.empty_field Empty
- else
  .results_table_wrapper
    = render "results_table"

app/views/admin/evaluation_sets/results_table.js.erb
$(".results_table_wrapper").html("<%= escape_javascript(render 'results_table.html') %>")

app/views/admin/evaluation_sets/results_twoaxis.html.haml
:css

  .d3_vis {
    margin-top:50px;
    background-color:#eee;
    border:1px solid #bbb;

  }

  .axis path,
  .axis line {
      fill: none;
      stroke: black;
      shape-rendering: crispEdges;
  }

  .axis text {
      font-family: sans-serif;
      font-size: 11px;
  }


  .pie image {
    cursor:pointer;
  }

.span X-Axis
%select.question_analysis.x_axis
  - @results.each_with_index do |r,i|
    %option{:value => i}
      = r.question.to_s

.span Y-Axis
%select.question_analysis.y_axis
  - @results.each_with_index do |r,i|
    %option{:value => i}
      = r.question.to_s


.d3_vis{:style=>"width:1100px;height:650px;"}

#evaluation_result_details



:javascript
  d3.select(".d3_vis").datum(#{@results.to_json})

app/views/admin/evaluation_sets/results_twoaxis_details.js.erb
$("#evaluation_result_details").html("<%= escape_javascript( render 'results_twoaxis_details') %>") 

$(".evaluation_result_pie").each(function(){
  var $elem = $(this)
  setTimeout( function(){
    draw_answers_pie.apply($elem,[
        $elem.data("yes-count"), 
        $elem.data("no-count"),
        $elem.data("na-count"),
        $elem.data("blank-count"),
        $elem.data("yes-comments"),
        $elem.data("no-comments"),
        $elem.data("na-comments"),
    ])
  }, 1);
})

$(".tooltip_trigger[title]").tooltip()